[workspace]
resolver = "2"
members = [
    "crates/lain-core",
    "crates/lain-identity",
    "crates/lain-noise",
    "crates/lain-nat",
    "crates/lain-dht",
    "crates/lain-discovery",
    "crates/lain-transport",
    "crates/lain-daemon",
    "crates/lain-cli",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/zmkjh/lain"

[workspace.dependencies]
thiserror = "2"
bytes = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
bincode = "1"
base62 = "2"
mdns-sd = "0.11"
ed25519-dalek = { version = "2", features = ["rand_core"] }
sha2 = "0.10"
rand = "0.8"
snow = "0.9"
quinn = { version = "0.11", features = ["rustls"] }
rustls = { version = "0.23", features = ["ring"] }
rcgen = "0.13"
clap = { version = "4", features = ["derive"] }
toml = "0.8"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.24"
sha1_smol = "1"
if-addrs = "0.13"
libc = "0.2"
hex = "0.4"
base64 = "0.22"
x25519-dalek = { version = "2", features = ["static_secrets"] }
socket2 = "0.5"
