[package]
name = "lain-identity"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lain-core = { path = "../lain-core" }
ed25519-dalek.workspace = true
sha2.workspace = true
rand.workspace = true
x25519-dalek.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
