[package]
name = "lain-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
async-trait = "0.1"
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
hex = "0.4"
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
