[package]
name = "lain-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lain-core = { path = "../lain-core" }
lain-noise = { path = "../lain-noise" }
lain-dht = { path = "../lain-dht" }
lain-nat = { path = "../lain-nat" }
thiserror.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["net", "sync", "time"] }
tracing.workspace = true
bytes.workspace = true
quinn.workspace = true
rustls.workspace = true
rcgen.workspace = true
sha2.workspace = true
ed25519-dalek.workspace = true
tokio-tungstenite.workspace = true
sha1_smol.workspace = true

[dev-dependencies]
lain-identity = { path = "../lain-identity" }
tokio = { workspace = true, features = ["net", "sync", "time", "rt", "macros"] }
